import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BootstrapClient from "@/components/bootstrap/client/BootstrapClient";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WeedDetect | AI Powered Agri App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={"container-fluid"}>
          <nav className="navbar navbar-expand-sm bg-white navbar-light fixed-top col-6">
              <div className="container-fluid pt-4">
                  <a className="navbar-brand" href="/">
                      <img src="/images/brand-logo.png" alt="Logo" style={{width:40}} className="rounded-pill"/>
                      WeeD DetecT
                  </a>
                  <ul className="navbar-nav">
                      <li className="nav-item">
                          <a className="nav-link" href="/">HOME</a>
                      </li>
                      <li className="nav-item">
                          <a className="nav-link" href="/how-it-works">HOW IT WORKS</a>
                      </li>
                      <li className="nav-item">
                          <a className="nav-link" href="/about-us">ABOUT US</a>
                      </li>
                  </ul>
              </div>
          </nav>
          <div className={'row'}>
              {children}
          </div>
      </div>
      <BootstrapClient/>
      </body>
    </html>
  );
}
